version: '2'
services:
    postgres:
        image: postgres
        ports:
            - '5433:5432'
    php:
        build: docker/php-fpm
        #tty: true
        ports:
            - '9002:9000'
        volumes:
            - ./:/var/www/symfony:cached
        links:
            - postgres
    nginx:
        build: docker/nginx
        ports:
            - '8080:80'
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx:cached
